# User Types
USER_TYPE_BUYER = 'BUYER'
USER_TYPE_SELLER = 'SELLER'

USER_TYPE_CHOICES = (
    (USER_TYPE_BUYER, 'Buyer'),
    (USER_TYPE_SELLER, 'Seller'),
)

# Phone validation
PHONE_REGEX = r'^\+?1?\d{9,15}$'
PHONE_ERROR_MESSAGE = "Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed."

# Field lengths - User Model
MAX_EMAIL_LENGTH = 255
MAX_NAME_LENGTH = 100
MAX_PHONE_LENGTH = 17
MAX_ADDRESS_LENGTH = 255
MAX_CITY_LENGTH = 100
MAX_STATE_LENGTH = 100
MAX_POSTAL_CODE_LENGTH = 20
MAX_COUNTRY_LENGTH = 100

# Field lengths - Seller Profile
MAX_BUSINESS_NAME_LENGTH = 255
MAX_TAX_ID_LENGTH = 50
MAX_BUSINESS_LICENSE_LENGTH = 100
MAX_BANK_ACCOUNT_LENGTH = 50
MAX_BANK_NAME_LENGTH = 100
MAX_BANK_ROUTING_LENGTH = 50

# Decimal field configurations
RATING_MAX_DIGITS = 3
RATING_DECIMAL_PLACES = 2
REVENUE_MAX_DIGITS = 12
REVENUE_DECIMAL_PLACES = 2